Repository mgear-dev/mgear4, pull requests merged in 2023-11, with the labels that each got.

#329 UE Gear and Shifter Documentation
  docs/requirements.txt
  docs/source/images/shifter/fbx_exporter/fbx_shifter.png
  docs/source/images/shifter/fbx_exporter/fbx_shifter_animation_cb.png
  docs/source/images/shifter/fbx_exporter/fbx_shifter_export_anim.png
  docs/source/images/shifter/fbx_exporter/fbx_shifter_export_geo.png
  docs/source/images/shifter/fbx_exporter/fbx_shifter_export_geo_partitions.png
  docs/source/images/shifter/fbx_exporter/fbx_shifter_maya_anim_layers.png
  docs/source/images/shifter/fbx_exporter/fbx_shifter_roots.png
  docs/source/images/shifter/fbx_exporter/fbx_shifter_ue_no_path.png
  docs/source/images/shifter/fbx_exporter/fbx_shifter_ue_path.png
  docs/source/images/shifter/fbx_exporter/fbx_shifter_ue_select_folder.png
  docs/source/images/uegear/asset_content_browser.png
  docs/source/images/uegear/asset_maya_import.png
  docs/source/images/uegear/asset_maya_import_tag.png
  docs/source/images/uegear/maya_level_asset_import.png
  docs/source/images/uegear/maya_level_asset_selection.png
  docs/source/images/uegear/maya_uegear_menu.png
  docs/source/images/uegear/sequencer_camera.png
  docs/source/images/uegear/sequencer_camera_selected.png
  docs/source/images/uegear/unreal_tag.png
  docs/source/index.rst
  docs/source/shifterUserDocumentation.rst
  docs/source/ueGearUserDocumentation.rst
Labels: documentation

#324 RBF Manager 2.0: Miscellaneous Improvements
  release/scripts/mgear/rigbits/menu.py
  release/scripts/mgear/rigbits/rbf_manager2/__init__.py
  release/scripts/mgear/rigbits/rbf_manager2/rbf_manager_ui.py
  release/scripts/mgear/rigbits/rbf_manager2/widget.py
Labels: bug, enhancement, New Feature

#326 Module bug fix: chain_IK_spline_variable_FK_stack_01
  release/scripts/mgear/shifter_classic_components/chain_IK_spline_variable_FK_stack_01/__init__.py
Labels: bug

#334 Shifter Partition UI: Updates correctly
  release/scripts/mgear/shifter/game_tools_fbx/partition_widgets.py
Labels: bug

#336 [Shifter FBX Exporter] Minor bugs
  release/scripts/mgear/shifter/game_tools_fbx/fbx_exporter.py
Labels: bug

#343 Made a metadata for rotateOrder
  release/scripts/mgear/core/anim_utils.py
  release/scripts/mgear/core/attribute.py
  release/scripts/mgear/shifter/component/__init__.py
Labels: bug

#345 [spine_ik_02] Added a vertical spacer on Component Settings
  release/scripts/mgear/shifter_classic_components/spine_ik_02/settingsUI.py
  release/scripts/mgear/shifter_classic_components/spine_ik_02/settingsUI.ui
Labels: bug
