Repository mgear-dev/mgear4, pull requests merged in 2023-09, with the labels that each got.

#252 Fixed a bug related to the Mirror Control Shape tool. reported by remicc
  release/scripts/mgear/rigbits/mirror_controls.py
Labels: bug

#281 ueGear - Camera and Object connectivity
  release/scripts/mgear/uegear/commands.py
  release/scripts/mgear/uegear/menu.py
Labels: New Feature

#291 Added get and set fps and warning dialog
  release/scripts/mgear/core/utils.py
  release/scripts/mgear/uegear/commands.py
Labels: enhancement
